name: Deploy Frontend to Azure VM

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to latest version
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Node.js
        uses: actions/setup-node@v4 # Updated to latest version
        with:
          node-version: 20
          cache: 'yarn' # Added caching for faster builds

      - name: Install dependencies
        run: yarn install

      - name: Run build task
        env:
          VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}
          VITE_PLATFORM_KEY: ${{ secrets.VITE_PLATFORM_KEY }}
          VITE_PLATFORM_VERSION: ${{ secrets.VITE_PLATFORM_VERSION }}
          VITE_PLATFORM_NAME: ${{ secrets.VITE_PLATFORM_NAME }}
        run: NODE_OPTIONS="--max-old-space-size=4096" CI=false yarn build

      - name: Deploy to Azure VM
        uses: easingthemes/ssh-deploy@main
        env:
          # Update these names in your GitHub Repository Secrets
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete --progress'
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.AZURE_VM_IP }}
          REMOTE_USER: ${{ secrets.AZURE_VM_USER }} # Usually 'azureuser' or 'ubuntu'
          TARGET: '/var/www/frontend/'
          SSH_ARGS: '-o StrictHostKeyChecking=no'
